In [1]:
import numpy as np
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [1]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype = np.float32)
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]


NameError: name 'np' is not defined

In [3]:
tf.set_random_seed(777)

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(10001) :
    cost_val, _ = sess.run([cost, train], feed_dict ={X : x_data, Y : y_data})
    if step % 1000 == 0 :
        print("step : %5d " %step, "\ncost: ", cost_val, "\n")

print("Your score will be ", sess.run(hypothesis, feed_dict={X : [[100, 70, 101]]}), " where x1 = 100, x2 = 70, x3 = 101")

step :     0  
cost:  21027.0 

step :  1000  
cost:  46.333565 

step :  2000  
cost:  24.722485 

step :  3000  
cost:  15.039153 

step :  4000  
cost:  10.57305 

step :  5000  
cost:  8.442335 

step :  6000  
cost:  7.387497 

step :  7000  
cost:  6.845183 

step :  8000  
cost:  6.5562315 

step :  9000  
cost:  6.397317 

step : 10000  
cost:  6.3075213 

Your score will be  [[187.42297]]  where x1 = 100, x2 = 70, x3 = 101


In [10]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X : [[100, 70, 101]]}))

Your score will be  [[187.42297]]


In [43]:
# another way for read files
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_dafaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_dafaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)


X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in range(10001) :
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y : y_batch})
    
    if step % 200 == 0:
        print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)
    
    
coord.request_stop()
coord.join(threads)


0 Cost :  128800.35 
Prediction : 
 [[-197.04523]
 [-228.76244]
 [-229.5541 ]
 [-252.67735]
 [-169.78413]
 [-127.43013]
 [-194.66417]
 [-152.49397]
 [-214.70746]
 [-203.43158]]
200 Cost :  49.88457 
Prediction : 
 [[151.41844]
 [189.95287]
 [183.04622]
 [196.93445]
 [149.31467]
 [108.21556]
 [142.30086]
 [ 97.89447]
 [176.90358]
 [159.85826]]
400 Cost :  45.192177 
Prediction : 
 [[151.41328 ]
 [189.76295 ]
 [182.93509 ]
 [197.04088 ]
 [148.9365  ]
 [108.2664  ]
 [142.77058 ]
 [ 98.793396]
 [176.9615  ]
 [160.39848 ]]
600 Cost :  41.016155 
Prediction : 
 [[151.41823 ]
 [189.57692 ]
 [182.83337 ]
 [197.14139 ]
 [148.57257 ]
 [108.301796]
 [143.21408 ]
 [ 99.642715]
 [177.00134 ]
 [160.88539 ]]
800 Cost :  37.293972 
Prediction : 
 [[151.43198]
 [189.39511]
 [182.74033]
 [197.23636]
 [148.2226 ]
 [108.32363]
 [143.63298]
 [100.44535]
 [177.02536]
 [161.32399]]
1000 Cost :  33.971645 
Prediction : 
 [[151.4533 ]
 [189.21768]
 [182.65515]
 [197.3261 ]
 [147.88622]
 [108.33362]
 [144.02869

9600 Cost :  5.0202165 
Prediction : 
 [[153.18092]
 [185.4263 ]
 [181.74416]
 [198.77763]
 [141.51634]
 [106.71811]
 [150.3944 ]
 [113.47826]
 [175.11505]
 [164.8152 ]]
9800 Cost :  4.9928594 
Prediction : 
 [[153.20131 ]
 [185.39693 ]
 [181.74214 ]
 [198.78636 ]
 [141.47139 ]
 [106.69536 ]
 [150.4322  ]
 [113.551605]
 [175.08836 ]
 [164.80971 ]]
10000 Cost :  4.9687777 
Prediction : 
 [[153.22087]
 [185.36891]
 [181.74028]
 [198.7947 ]
 [141.4286 ]
 [106.67354]
 [150.46812]
 [113.62131]
 [175.06277]
 [164.80412]]
