In [1]:
import tensorflow as tf
import numpy as np

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_data = np.array([[0], [1], [1], [0]])

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_normal([2, 2]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([2]), name = 'bias1')

layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)


W2 = tf.Variable(tf.random_normal([2, 1]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([1]), name = 'bias2')

hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

In [8]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediced = tf.cast(hypothesis > 0.5, dtype= tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediced, Y), dtype=tf.float32))

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    
    for step in range(20001) :
        sess.run(train, feed_dict={X : x_data, Y : y_data})
        
        if step == 0 :
            print("step : %-5d" %step, sess.run(cost, feed_dict = {X : x_data, Y : y_data}), "\n")
            print("W1 : \n", sess.run(W1))
            print("W2 : \n", sess.run(W2))
            
            h, c, a = sess.run([hypothesis, prediced, accuracy], feed_dict={X : x_data, Y : y_data})
            print("\nX data : [[0, 0], [0, 1], [1, 0], [1, 1]]")
            print("Y data : [[0], [1], [1], [0]]")
            print("\nCorrect : \n", c, "\nAccuracy : \n", a)
            
        if step == 20000 :
            print("step : %-5d" %step, "cost : ", sess.run(cost, feed_dict = {X : x_data, Y : y_data}), "\n")
            print("W1 : \n", sess.run(W1))
            print("W2 : \n", sess.run(W2))
            
            h, c, a = sess.run([hypothesis, prediced, accuracy], feed_dict={X : x_data, Y : y_data})
            print("\nX data : [[0, 0], [0, 1], [1, 0], [1, 1]]")
            print("Y data : [[0], [1], [1], [0]]")
            print("\nCorrect : \n", c, "\nAccuracy : \n", a)

step : 0     0.7798612 

W1 : 
 [[-0.9592006  -0.75864214]
 [-0.26752168  0.37691098]]
W2 : 
 [[-0.55570126]
 [-0.9239968 ]]

X data : [[0, 0], [0, 1], [1, 0], [1, 1]]
Y data : [[0], [1], [1], [0]]

Correct : 
 [[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy : 
 0.5
step : 20000 cost :  0.00596974 

W1 : 
 [[-6.418283  -7.223703 ]
 [ 6.0379868  7.1317887]]
W2 : 
 [[ 11.739497]
 [-11.085879]]

X data : [[0, 0], [0, 1], [1, 0], [1, 1]]
Y data : [[0], [1], [1], [0]]

Correct : 
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy : 
 1.0
